# Generated by Django 5.0.2 on 2024-02-15 18:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('moderator', 'moderator'), ('member', 'member')], max_length=23, null=True, verbose_name='Роль пользователя'),
        ),
    ]
