# Generated by Django 5.0.2 on 2024-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('moderator', 'Moderator')], default='teacher', max_length=150, null=True),
        ),
    ]
