version: '3'
services:
  postgre_SQL:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=19290
      - POSTGRES_USER='postgres'
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    container_name: postgre_SQL
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d educate_module -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build: .
    tty: true
    command: sh -c "sleep 5 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      postgre_SQL:
        condition: service_healthy

volumes:
  pg_data:
