# Generated by Django 4.2.10 on 2024-02-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='educational_modules/', verbose_name='Фото'),
        ),
    ]
