# Generated by Django 4.2.10 on 2024-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_remove_module_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
