# Generated by Django 4.2.9 on 2024-02-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_module_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='number',
        ),
    ]
