# Generated by Django 4.2.9 on 2024-02-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_remove_module_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
