# Generated by Django 5.0.2 on 2024-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='educational_modules/category/photo', verbose_name='Ф   ото'),
        ),
    ]
